<?xml version="1.0"?>

<robot name="jasmine_ugv" xmlns:xacro="http://ros.org/wiki/xacro">
    
    <!-- Included URDF Files -->
    <xacro:include filename="$(find hector_tracked_vehicles_description)/urdf/jasmine_ugv_base.urdf.xacro" />
    <xacro:include filename="$(find hector_tracked_vehicles_description)/urdf/jasmine_2018_structure_addons.urdf.xacro" />
    <xacro:include filename="$(find hector_components_description)/urdf/vlp16_mount.urdf.xacro.xml"/>
    <xacro:include filename="$(find hector_components_description)/urdf/tracker_sensor_head.urdf.xacro.xml"/>
    
    <xacro:include filename="$(find hector_tracked_vehicles_description)/calibrations/spin_lidar_calibration.urdf.xacro"/>
    <xacro:include filename="$(find hector_tracked_vehicles_description)/urdf/jasmine_2018_ugv_arm.urdf.xacro" />
    <xacro:include filename="$(find hector_sensors_description)/urdf/realsense_d435_camera.urdf.xacro"/>

    <!--file
    <xacro:property name="vlp16_calibration">
      <origin xyz="0.0 0.0 0.09446" rpy="${M_PI*0.250} 0.0 ${M_PI}"/>
    </xacro:property>
    -->
    
    <xacro:arg name="add_default_geom" default="true"/>
    <xacro:arg name="add_containment_self_filter_geom" default="false"/>
    <xacro:arg name="add_raycast_self_filter_geom" default="false"/>
    
    <xacro:jasmine_ugv_macro>
<!--      <xacro:arg name="add_default_geom" default="$(arg add_default_geom)"/>
      <xacro:arg name="add_containment_self_filter_geom_" default="$(arg add_containment_self_filter_geom)"/>
      <xacro:arg name="add_raycast_self_filter_geom" default="$(arg add_raycast_self_filter_geom)"/>-->
    </xacro:jasmine_ugv_macro>
    
    
    <!-- Helper links to view robot from front and side with top-down ortho in rviz -->
<!--    <joint name="base_link_side_joint" type="fixed">
      <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
        
      <parent link="base_link"/>
      <child link="base_link_side" />
    </joint>
    
    <link name="base_link_side"/>
    
    <joint name="base_link_front_joint" type="fixed">
      <origin xyz="0 0 0" rpy=" 0 ${-M_PI/2} 0" />
        
      <parent link="base_link"/>
      <child link="base_link_front" />
    </joint>
    
    <link name="base_link_front"/>-->
    
    <xacro:manipulator_arm_macro parent="base_link">
      <origin xyz="-0.1618 -0.06875 0.01315" rpy="0.0 0.0 ${M_PI/2}" />
    </xacro:manipulator_arm_macro>
    
    <xacro:tracker_sensor_head_macro parent="base_link">
      <origin xyz="${+0.18 } 0.04 ${0.05}" rpy="0.0 -0.0 ${0.0}"/>    
    </xacro:tracker_sensor_head_macro>

    <xacro:jasmine_2018_structure_addons_macro parent="base_link" alu_profile_collision_size_factor="2.0">
     <origin xyz="${base_size_x - 0.12 - computer_box_width/2} 0 0.025" rpy="0 0 0"/>       
    </xacro:jasmine_2018_structure_addons_macro>
        
<!--    <xacro:realsense_d435_camera_comprehensive_params name="manipulation_rgbd_cam" parent="base_link" image_topic="image_rect_color" depth_points_topic="depth/points" min_range="0.3" max_range="9.0" update_rate="20">
      <origin xyz="-0.08 -0.0085 0.454" rpy="0.0 ${25*M_PI/180.0} ${M_PI}"/>
    </xacro:realsense_d435_camera_comprehensive_params>-->
        


    
</robot>
