<?xml version="1.0"?>

<robot
    xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
    xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
    xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface">
  <property name="flipper_base_mass" value="2.0"/>
  <property name="flipper_x" value="0.4"/>
<property name="flipper_y" value="0.1"/>
<property name="flipper_z" value="0.1"/>
<property name="wheel_radius_first" value="0.093" />
<property name="wheel_radius_second" value="0.09" />
    <property name="wheel_radius_third" value="0.08" />
<property name="wheel_intersect_flipper" value="${((flipper_x-2*wheel_radius_first-2*wheel_radius_second-2*wheel_radius_third)/2)}" />
<property name="wheel_pos_second" value="${2*wheel_radius_first+wheel_intersect_flipper}" />
    <macro name="obelix_flipper_wheels_macro" params="parent name front *origin">
    
 <!-- front is either 1 (for front flipper) or -1 (for back flipper) -->
<joint name="${parent}_${name}_flipper_joint" type="revolute">    
<insert_block name="origin"/>
      <axis xyz="0 1 0"/>
      <limit lower="${-90 * M_PI / 180}" upper="${90 * M_PI / 180}"
             effort="204" velocity="${1.0 * 110 * M_PI / 180}" />
        <safety_controller soft_lower_limit="${-168 * M_PI / 180}"
                         soft_upper_limit="${168 * M_PI / 180}"
                         k_position="${100}"
                         k_velocity="${2}"/>
     
      <parent link="${parent}"/>
      <child link="left_${name}_flipper_base_link"/>
    </joint>



<link name="left_${name}_flipper_base_link">
<origin xyz="0 0 0" rpy="0 0 0" />
           
        </link>

<gazebo reference="left_${name}_flipper_link">
      <material>Gazebo/Green</material>
    </gazebo>

 <tracked_wheel parent="left_${name}_flipper_base_link" prefix="first_${name}_left" offset_x= "0" offset_y = "0" offset_z = "0" reflect="1" wheel_radius="${wheel_radius_first}"/>

<tracked_wheel parent="left_${name}_flipper_base_link" prefix="second_${name}_left" offset_x= "${front*(2*wheel_radius_first+((flipper_x-2*wheel_radius_first-2*wheel_radius_second-2*wheel_radius_third)/2))}" offset_y = "0" offset_z = "0" reflect="1" wheel_radius="${wheel_radius_second}"/>

<tracked_wheel parent="left_${name}_flipper_base_link" prefix="third_${name}_left" offset_x= "${front*(flipper_x-wheel_radius_third+((flipper_x-2*wheel_radius_first-2*wheel_radius_second-2*wheel_radius_third)/2))}" offset_y = "0" offset_z = "0" reflect="1" wheel_radius="${wheel_radius_second}"/>


 
<joint name="right_${name}_flipper_joint" type="fixed">    
      <origin xyz="0 ${-2*(base_size_y*0.5+wheel_offset_y+0.5*wheel_size_y)} 0" rpy="0 0 0" />
     
      <parent link="left_${name}_flipper_base_link"/>
      <child link="right_${name}_flipper_base_link"/>
    </joint>

<link name="right_${name}_flipper_base_link">
<origin xyz="0 0 0" rpy="0 0 0" />
       
        </link>

<tracked_wheel parent="right_${name}_flipper_base_link" prefix="first_${name}_right" offset_x= "0" offset_y = "0" offset_z = "0" reflect="1" wheel_radius="${wheel_radius_first}"/>

<tracked_wheel parent="right_${name}_flipper_base_link" prefix="second_${name}_right" offset_x= "${front*(2*wheel_radius_first+((flipper_x-2*wheel_radius_first-2*wheel_radius_second-2*wheel_radius_third)/2))}" offset_y = "0" offset_z = "0" reflect="1" wheel_radius="${wheel_radius_second}"/>

<tracked_wheel parent="right_${name}_flipper_base_link" prefix="third_${name}_right" offset_x= "${front*(flipper_x-wheel_radius_third+((flipper_x-2*wheel_radius_first-2*wheel_radius_second-2*wheel_radius_third)/2))}" offset_y = "0" offset_z = "0" reflect="1" wheel_radius="${wheel_radius_second}"/>

<gazebo reference="right_${name}_flipper_link">
      <material>Gazebo/Green</material>
    </gazebo>


   
    </macro>
</robot>
