<?xml version="1.0"?>

<robot
    xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
    xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
    xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface">
  <property name="flipper_base_mass" value="2.0"/>
  <property name="flipper_x" value="0.3"/>
<property name="flipper_y" value="0.1"/>
<property name="flipper_z" value="0.15"/>
    <macro name="obelix_flipper_macro" params="parent name front *origin">
    
 <!-- front is either 1 (for front flipper) or -1 (for back flipper) -->
<!-- <joint name="${parent}_${name}_flipper_joint" type="fixed">   --> 
<joint name="${parent}_${name}_flipper_joint" type="revolute">    
<insert_block name="origin"/>
      <axis xyz="0 1 0"/>
      <limit lower="${-90 * M_PI / 180}" upper="${90 * M_PI / 180}"
             effort="204" velocity="${1.0 * 110 * M_PI / 180}" />
        <safety_controller soft_lower_limit="${-168 * M_PI / 180}"
                         soft_upper_limit="${168 * M_PI / 180}"
                         k_position="${100}"
                         k_velocity="${2}"/>
     
      <parent link="${parent}"/>
      <child link="left_${name}_flipper_base_link"/>
    </joint>

<link name="left_${name}_flipper_base_link">
<origin xyz="0 0 0" rpy="0 0 0" />
                <inertial>
                <mass value="1.0" />
                <origin xyz="0.0 0.0 0.5" rpy="0 0 0" />
                <inertia ixx="0.005" ixy="0.0" ixz="0.0"
                         iyy="0.005" iyz="0.0" 
                         izz="0.005" />
            </inertial>
            
            <collision name='collision'>
             <origin xyz="${front*flipper_x*0.5} 0.0 0" rpy="0 0 0" />
          	<geometry>
            		<box size="${flipper_x} ${flipper_y} ${flipper_z}"/>
          	</geometry>
            </collision>

            <visual name='visual'>
            	<origin xyz="${front*flipper_x*0.5} 0.0 0" rpy="0 0 0" />
          	<geometry>
            		<box size="${flipper_x} ${flipper_y} ${flipper_z}"/>
          	</geometry>
          	<material name="Grey" >
                    <color rgba="0.8 0.8 0.8 1"/>
                </material>
            </visual> 
        </link>

<gazebo reference="left_${name}_flipper_link">
      <material>Gazebo/Green</material>
    </gazebo>

   <joint name="right_${name}_flipper_joint" type="fixed">    
      <origin xyz="0 ${-2*(base_size_y*0.5+wheel_offset_y+0.5*wheel_size_y)} 0" rpy="0 0 0" />
     
      <parent link="left_${name}_flipper_base_link"/>
      <child link="right_${name}_flipper_base_link"/>
    </joint>

<link name="right_${name}_flipper_base_link">
<origin xyz="0 0 0" rpy="0 0 0" />
                <inertial>
                <mass value="1.0" />
                <origin xyz="0.0 0.0 0.5" rpy="0 0 0" />
                <inertia ixx="0.005" ixy="0.0" ixz="0.0"
                         iyy="0.005" iyz="0.0" 
                         izz="0.005" />
            </inertial>
            
            <collision name='collision'>
             <origin xyz="${front*flipper_x*0.5} 0.0 0" rpy="0 0 0" />
          	<geometry>
            		<box size="${flipper_x} ${flipper_y} ${flipper_z}"/>
          	</geometry>
            </collision>

            <visual name='visual'>
            	<origin xyz="${front*flipper_x*0.5} 0.0 0" rpy="0 0 0" />
          	<geometry>
            		<box size="${flipper_x} ${flipper_y} ${flipper_z}"/>
          	</geometry>
          	<material name="Grey" >
                    <color rgba="0.8 0.8 0.8 1"/>
                </material>
            </visual> 
        </link>

<gazebo reference="right_${name}_flipper_link">
      <material>Gazebo/Green</material>
    </gazebo>


   
    </macro>
</robot>
