cloud_filter_chain:
  - name: robot_body_filter
    type: robot_body_filter/RobotBodyFilterPointCloud2
    params:
      bounding_box/publish_cut_out_pointcloud: false
      bounding_box/compute: false
      bounding_box/marker: false
      bounding_box/debug: false
      bounding_sphere/publish_cut_out_pointcloud: false
      bounding_sphere/compute: false
      bounding_sphere/marker: false
      bounding_sphere/debug: false
      oriented_bounding_box/publish_cut_out_pointcloud: false
      oriented_bounding_box/compute: false
      oriented_bounding_box/marker: false
      oriented_bounding_box/debug: false
      local_bounding_box/publish_cut_out_pointcloud: false
      local_bounding_box/compute: false
      local_bounding_box/marker: false
      local_bounding_box/debug: false
      debug/marker/contains: false
      debug/marker/shadow: false
      debug/pcl/clip: true
      debug/pcl/shadow: true
      debug/pcl/inside: true
      sensor/point_by_point: false
      sensor/min_distance: 0.15
      sensor/max_distance: 0
      frames/sensor: spin_lidar_lidar_mount_link_fixed
      frames/filtering: spin_lidar_lidar_mount_link_fixed
      frames/output: spin_lidar_lidar_mount_link_fixed
      frames/fixed: spin_lidar_lidar_mount_link_fixed
      body_model/inflation/scale: 1.0
      body_model/inflation/padding: 0.02
      body_model/robot_description_param: /robot_description
      filter/do_clipping: true
      filter/do_contains_test: true
      filter/do_shadow_test: true
      only_links:
        - chassis_link
        - left_track_link
        - right_track_link
        - autonomy_box_link
        - arm_pitch_link_0
        - arm_pitch_link_1
        - arm_pitch_link_2
        - arm_roll_link
        - arm_yaw_link
        - gripper_finger_link_0
        - gripper_finger_link_1
        - gripper_palm_link
        - sensor_head_yaw_link
        - sensor_head_pitch_link
        - arm_rgbd_cam_link
        - arm_thermal_cam_frame
        
        
