min_sensor_dist: 0.1
self_see_default_padding: 0.10
self_see_default_scale: 1.0
self_see_links:
- name: base_link
- name: left_front_flipper_base_link
- name: left_rear_flipper_base_link
- name: right_front_flipper_base_link
- name: right_rear_flipper_base_link


