min_sensor_dist: .15
self_see_default_padding: 0.1
self_see_default_scale: 1.0
self_see_links:
- name: chassis_link
- name: arm_link_0
- name: arm_link_1
- name: arm_link_2
- name: arm_link_3
- name: arm_link_4
- name: sensor_head_yaw_link
- name: arm_rgbd_link
- name: arm_thermal_frame
- name: spin_lidar_link_hokuyo_laser_frame
- name: stab_laser_roll_link
- name: stab_laser_frame
- name: structure_addons_link




